### Register a User
POST https://dagapis.aihoply.com/api/v1/register
Content-Type: application/json

{
  "email": "nhattruong@aihoply.com"
}

### Send OTP
POST https://dagapis.aihoply.com/api/v1/send-otp
Content-Type: application/json

{
  "email": "nhattruong@aihoply.com"
}

### Verify OTP
# Replace <OTP> with the actual OTP received in the email
POST https://dagapis.aihoply.com/api/v1/verify-otp
Content-Type: application/json

{
  "email": "nhattruong@aihoply.com",
  "otp": "286290"
}

### Token Check
# Replace <TOKEN> with the actual token received after OTP verification
GET https://dagapis.aihoply.com/api/v1/token-check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuaGF0dHJ1b25nQGFpaG9wbHkuY29tIiwiZXhwIjoxNzIxODE0MjQ0fQ._152BOU69_lvo1Ly2vEDs_AOv68pmJMhImrZ62GEdlo

### Logout
# Replace <TOKEN> with the actual token received after OTP verification
POST https://dagapis.aihoply.com/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuaGF0dHJ1b25nQGFpaG9wbHkuY29tIiwiZXhwIjoxNzIxODE0MjQ0fQ._152BOU69_lvo1Ly2vEDs_AOv68pmJMhImrZ62GEdlo
